### ISSUE TITLE
Problem: signature verification failed with chainlibpy

### ISSUE THREAD

**Issue by Galadrin** [crypto-org-chain/chainlibpy#9]
**Describe the bug**
Using the chainlibpy, the Tx requests reply with `signature verification failed; unauthorized error (code 4)
The issue does not happen immediately.

**To Reproduce**
Using sample code in chainlibpy, execute a while true loop to create new Tx each loop.
On error, catch error 19, 20 and 4.
19 and 20 are expected.
Error 4 are about signature vérification.

**Expected behavior**

**Screenshots**
https://chain.crypto.com/explorer/crossfire/tx/9D27BF51E0E76380C37C1053278DC876EEEE7AE6628B39D6952DBF46886C7B3A

**Desktop (please complete the following information):**
 - OS: Ubuntu 12.04

**Comment by linfeng-crypto** [comment]
hi @Galadrin, I can't reproduce the sign error, I only get the error code 19, can you past the code in your loop?

**Comment by Galadrin** [comment]
Hi @linfeng-crypto 
The issue was openned during the Crossfire event. this can be relative the the high load of the chain.

I will try to run my code again to check if the problem occured again on Croeseid.

I need to do some cleanup before sharing the code.

**Comment by Galadrin** [comment]
Hi,
we have done some load test since 3 days.
I can confirm the code 4.

have modified the chainlibpy to add some options.
https://github.com/Galadrin/chainlibpy

my flooding script if available in the following project :
https://github.com/Galadrin/chain-tx

please update your seed L69.

**Comment by linfeng-crypto** [comment]
hi, @Galadrin I think the wrong `sequence` caused the error 4 unauthorized
in your loop, for example,  sign tx and broadcast ok from sequence 1-100, when there's something wrong, pool is full for example, you `break` out of the loop `for seq in range(sequence, stop_at):`, then continue in the loop `while True`, it will get the sequence again from `URL`, but now the sequence in URL still need some time to update to 100, so you get the wrong sequence, 98 for example, actually it should be 101, then the tx with sequence 98 is wrong, and get the error code 4.

**Comment by linfeng-crypto** [comment]
hi, @Galadrin I think the wrong `sequence` caused the error 4 unauthorized
in your loop, for example,  sign tx and broadcast ok from sequence 1-100, but if you break when there's something wrong, pool is full for example, you break from the loop `for seq in range(sequence, stop_at):`, then continue in the `while True`, it will get the sequence from `URL`, but now the sequence in URL still need some time to update it to 100, so you get the wrong sequence, 98 for example, actually it should be 101, then the tx with sequence 98 is wrong, and get the error code 4.
